import { timestamp } from 'rxjs/operators';

export class AppSettings {
    public static API_NCB_SMART = '/NCB-smart';
    public static UPLOAD_IMAGE = {
        file_size: 10 * 1024 * 1024,
        file_ext: 'image/jpg,image/png,image/jpeg,image/gif',
        height: 300,
        width: 300,
    };
    // isC: CREATE
    // isR: READ
    // isU: UPDATE
    // isD: DELETE
    // isA: approved
    public static listRoles = [
        {
            code: 'NGUOI_DUNG',
            name: 'Người dùng',
            isAll: false,
            isC: false,
            isR: false,
            isU: false,
            isD: false,
            isA: false,
            menu: 'QUAN_TRI',
        },
        {
            code: 'PHAN_QUYEN',
            name: 'Phân quyền',
            isAll: false,
            isC: false,
            isR: false,
            isU: false,
            isD: false,
            isA: false,
            menu: 'QUAN_TRI',
        },
        {
            code: 'CHI_NHANH',
            name: 'Chi nhánh',
            isAll: false,
            isC: false,
            isR: false,
            isU: false,
            isD: false,
            isA: false,
            menu: 'GIAO_DICH',
        },
        {
            code: 'NGH_CHUYEN_KHOAN',
            name: 'Ngân hàng CK',
            isAll: false,
            isC: false,
            isR: false,
            isU: false,
            isD: false,
            isA: false,
            menu: 'GIAO_DICH',
        },
        {
            code: 'NHA_CC_DICH_VU',
            name: 'NCC dịch vụ',
            isAll: false,
            isC: false,
            isR: false,
            isU: false,
            isD: false,
            isA: false,
            menu: 'GIAO_DICH',
        },
        {
            code: 'HINH_THE',
            name: 'Hình ảnh, phôi thẻ',
            isAll: false,
            isC: false,
            isR: false,
            isU: false,
            isD: false,
            isA: false,
            menu: 'THAM_SO',
        },
        {
            code: 'GOI_SP',
            name: 'Gói sản phẩm',
            isAll: false,
            isC: false,
            isR: false,
            isU: false,
            isD: false,
            isA: false,
            menu: 'KHACH_HANG',
        },
        {
            code: 'GOI_KH_SU_DUNG',
            name: 'Gói KH sử dụng',
            isAll: false,
            isC: false,
            isR: false,
            isU: false,
            isD: false,
            isA: false,
            menu: 'KHACH_HANG',
        },
        {
            code: 'DV_KH_DK',
            name: 'DVKH đăng ký',
            isAll: false,
            isC: false,
            isR: false,
            isU: false,
            isD: false,
            isA: false,
            menu: 'KHACH_HANG',
        },
        {
            code: 'KHUYEN_MAI',
            name: 'KM, ưu đãi',
            isAll: false,
            isC: false,
            isR: false,
            isU: false,
            isD: false,
            isA: false,
            menu: 'KHACH_HANG',
        },
        {
            code: 'TT_KH',
            name: 'TT khách hàng',
            isAll: false,
            isC: false,
            isR: false,
            isU: false,
            isD: false,
            isA: false,
            menu: 'KHACH_HANG',
        },
        {
            code: 'SO_TONG_DAI',
            name: 'Số tổng đài',
            isAll: false,
            isC: false,
            isR: false,
            isU: false,
            isD: false,
            isA: false,
            menu: 'THAM_SO',
        },
        {
            code: 'NOTIFY',
            name: 'Notify(in App)',
            isAll: false,
            isC: false,
            isR: false,
            isU: false,
            isD: false,
            isA: false,
            menu: 'THAM_SO',
        },
        {
            code: 'CRONJOB',
            name: 'Cấu hình Schedule',
            isAll: false,
            isC: false,
            isR: false,
            isU: false,
            isD: false,
            isA: false,
            menu: 'THAM_SO',
        },
        {
            code: 'VERSION_APP',
            name: 'Version App',
            isAll: false,
            isC: false,
            isR: false,
            isU: false,
            isD: false,
            isA: false,
            menu: 'THAM_SO'
        },
        {
            code: 'DIEU_KHOAN',
            name: 'DK sử dụng',
            isAll: false,
            isC: false,
            isR: false,
            isU: false,
            isD: false,
            isA: false,
            menu: 'TRA_CUU',
        },
        {
            code: 'MANG_LUOI_CN',
            isAll: false,
            isC: false,
            isR: false,
            isU: false,
            isD: false,
            isA: false,
            name: 'DS chi nhánh',
            menu: 'TRA_CUU',
        },
        {
            code: 'HD_SU_DUNG',
            isAll: false,
            isC: false,
            isR: false,
            isU: false,
            isD: false,
            isA: false,
            name: 'HD sử dụng',
            menu: 'TRA_CUU',
        },
        {
            code: 'THANH_PHO',
            name: 'Thành phố',
            isAll: false,
            isC: false,
            isR: false,
            isU: false,
            isD: false,
            isA: false,
            menu: 'TRA_CUU',
        },
        {
            code: 'TT_QA',
            isAll: false,
            isC: false,
            isR: false,
            isU: false,
            isD: false,
            isA: false,
            name: 'Q&As',
            menu: 'TRA_CUU',
        },
        {
            code: 'GOP_Y_LOI',
            isAll: false,
            isC: false,
            isR: false,
            isU: false,
            isD: false,
            isA: false,
            name: 'Góp ý - lỗi',
            menu: 'TRA_CUU',
        },
        {
            code: 'BANNER',
            isAll: false,
            isC: false,
            isR: false,
            isU: false,
            isD: false,
            isA: false,
            name: 'Banner',
            menu: 'TRA_CUU',
        },
        {
            code: 'RESET_PASSWORD',
            name: 'Người dùng',
            isAll: false,
            isC: false,
            isR: false,
            isU: false,
            isD: false,
            isA: false,
            menu: 'QUAN_TRI',
        },
        {
            code: 'QR_SERVICE',
            name: 'DV thanh toán',
            isAll: false,
            isC: false,
            isR: false,
            isU: false,
            isD: false,
            isA: false,
            menu: 'KHACH_HANG',
        },
        {
            code: 'QR_COUPON',
            name: 'DVTT giảm giá',
            isAll: false,
            isC: false,
            isR: false,
            isU: false,
            isD: false,
            isA: false,
            menu: 'KHACH_HANG',
        },
        {
            code: 'QR_MERCHANT',
            name: 'NCC dịch vụ QR',
            isAll: false,
            isC: false,
            isR: false,
            isU: false,
            isD: false,
            isA: false,
            menu: 'KHACH_HANG',
        },

        {
            code: 'INVITE',
            name: 'GT bạn bè',
            isAll: false,
            isC: false,
            isR: false,
            isU: false,
            isD: false,
            isA: false,
            menu: 'KHACH_HANG',
        },
        {
            code: 'NOTIFY_USER',
            name: 'TB người dùng',
            isAll: false,
            isC: false,
            isR: false,
            isU: false,
            isD: false,
            isA: false,
            menu: 'KHACH_HANG',
        },
        {
            code: 'P_PROMO',
            name: 'DTTG ưu đãi',
            isAll: false,
            isC: false,
            isR: false,
            isU: false,
            isD: false,
            isA: false,
            menu: 'KHACH_HANG',
        },
         {
        code: 'HP_MANAGER',
        name: 'Up load học phí',
        isAll: false,
        isC: false,
        isR: false,
        isU: false,
        isD: false,
        isA: false,
        menu: 'HOC_PHI',
        },
        {
        code: 'HP_COST',
        name: 'Khoản thanh toán',
        isAll: false,
        isC: false,
        isR: false,
        isU: false,
        isD: false,
        isA: false,
        menu: 'HOC_PHI',
        },
        {
        code: 'HP_SCHOOL',
        name: 'Trường học',
        isAll: false,
        isC: false,
        isR: false,
        isU: false,
        isD: false,
        isA: false,
        menu: 'HOC_PHI',
        },
        {
        code: 'HP_FACULTY',
        name: 'Khoa',
        isAll: false,
        isC: false,
        isR: false,
        isU: false,
        isD: false,
        isA: false,
        menu: 'HOC_PHI',
        },
        {
        code: 'HP_CLASS',
        name: 'Lớp học',
        isAll: false,
        isC: false,
        isR: false,
        isU: false,
        isD: false,
        isA: false,
        menu: 'HOC_PHI',
        },
    ];
    public static getListRoles() {
        const getListRoles = localStorage.getItem('roles')
            ? JSON.parse(localStorage.getItem('roles'))
            : '';
        return getListRoles;
    }
}
